#ifndef CONSTANTS_H
#define CONSTANTS_H

#define BUFFER_SIZE 4096
#define MAX_LEN_PSEUDO 31
#define BORNES_PORT_MAX 65535 
#define BORNES_PORT_MIN 1
#define MAX_LEN_MESSAGE 1054
#define PORT_PAR_DEFAULT 1234 

#endif // CONSTANTS_H
