#!/bin/bash

DESCRIPTION="chat-bot destinataire [pseudo]"

if (( $# < 1 )) || (( $# > 2 )) ; then
   echo "$DESCRIPTION" >&2
   exit 1
fi

destinataire="$1"
nom="$2"

if (( $# < 2 )); then
   nom="bot"
fi

commande-liste-mots() {
   while IFS= read -r ligne; do
      mot="${ligne%% *}"

      if [[ "$mot" == "$1" ]]; then
         echo "${ligne#* }"
         return 0
      fi
   done < liste-bot.txt

   echo "🤖 ?"
}

bot() {
   destinataire="$1"

   while IFS= read -r ligne; do
      # Supprimer le nom de l'interlocutrice/interlocuteur
      commande="${ligne#*] }"
      case "$commande" in
         "liste")
            ls
            ;;

         "au revoir")
            exit 0
            ;;

         li\ *)
            reponse="$(cat "${commande#li }" 2>&1)"
            if [[ "${reponse: -1}" != "\n" ]]; then
               echo "$reponse"
            else
               echo -n "$reponse"
            fi
            ;;
         "qui suis-je")
            echo "$destinataire"
            ;;

         *)
            commande-liste-mots "$commande"
            ;;
      esac
   done
}

fifodir=$(mktemp -d)
botpipe="$fifodir/bot-pipe"
mkfifo "$botpipe"
./chat "$nom" "$destinataire" --bot < "$botpipe" | bot "$destinataire" > "$botpipe"

rm -r "$fifodir"
